runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: "2.3.5"

inbound_services:
- mail

handlers:
- url: /_ah/mail/info@fiftytwo-peregrine\.appspotmail\.com
  script: email_handler.app
- url: /fetch
  script: fetch.app
- url: /.*
  script: main.app
